[package]
name = "winrs"
version = "0.1.0"
edition = "2024"
license = "MIT"


[dependencies]
softbuffer = "0.4.8"

[dependencies.winit]
version = "0.30.12"
default-features = false
features = ["wayland", "rwh_06"]
